async function getData() {
 return [
  { name: "Acerola" },
  { name: "Açai" },
  { name: "Apple" },
  { name: "Apricot" },
  { name: "Avocado" },
  { name: "Banana" },
  { name: "Blackberry" },
  { name: "Blueberry" },
  { name: "Carambola" },
  { name: "Cherry" },
  { name: "Coconut" },
  { name: "Cranberry" },
  { name: "Date" },
  { name: "Dragon Fruit" },
  { name: "Fig" },
  { name: "Grape" },
  { name: "Guava" },
  { name: "Jabuticaba" },
  { name: "Kiwi" },
  { name: "Lemon" },
  { name: "Lime" },
  { name: "Lychee" },
  { name: "Mango" },
  { name: "Mandarine" },
  { name: "Melon" },
  { name: "Orange" },
  { name: "Passionfruit" },
  { name: "Papaya" },
  { name: "Peach" },
  { name: "Persimmon" },
  { name: "Pineapple" },
  { name: "Plum" },
  { name: "Pomegranate" },
  { name: "Pomelo" },
  { name: "Rapsberry" },
  { name: "Strawberry" },
  { name: "Tamarind" },
 ];
}

export const searchService = {
 getData,
};
